### ISSUE TITLE
Bug Report: There is a problem with "meta" for MediaAttachments

### ISSUE THREAD

**Issue by Kraigo** [mastodon-dart/mastodon-api#149]
# 1. Current bug behavior

# 2. Expected behavior

# 3. Steps to reproduce

# 4. Flutter doctor output

```terminal
Output of: flutter doctor -v
```

# 5. More environment information

# 6. Log information

```terminal
Could not create `_$_MediaAttachment`.
There is a problem with "meta".
type 'Null' is not a subtype of type 'Map<dynamic, dynamic>' in type cast
#0      $checkedConvert
checked_helpers.dart:92
#1      $checkedCreate.checkedConvert
checked_helpers.dart:29
#2      _$$_MediaAttachmentFromJson.<anonymous closure>
media_attachment.g.dart:22
#3      $checkedCreate.<anonymous closure>
checked_helpers.dart:34
#4      $checkedNew
checked_helpers.dart:52
#5      $checkedCreate
checked_helpers.dart:31
#6      _$$_MediaAttachmentFromJson
media_attachment.g.dart:11
#7      new _$_MediaAttachment.fromJson
media_attachment.freezed.dart:235
#8      _$MediaAttachmentFromJson
media_attachment.freezed.dart:18
#9      new MediaAttachment.fromJson
media_attachment.dart:48
#10     _$$_StatusFromJson.<anonymous closure>.<anonymous closure>.<anonymous closure>
status.g.dart:59
#11     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#12     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#13     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#13     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#14     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#15     new List.of (dart:core-patch/array_patch.dart:51:28)
#16     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#17     _$$_StatusFromJson.<anonymous closure>.<anonymous closure>
status.g.dart:61
#18     $checkedConvert
checked_helpers.dart:88
#19     $checkedCreate.checkedConvert
checked_helpers.dart:29
#20     _$$_StatusFromJson.<anonymous closure>
status.g.dart:56
#21     $checkedCreate.<anonymous closure>
checked_helpers.dart:34
#22     $checkedNew
checked_helpers.dart:52
#23     $checkedCreate
checked_helpers.dart:31
#24     _$$_StatusFromJson
status.g.dart:11
#25     new _$_Status.fromJson
status.freezed.dart:588
#26     _$StatusFromJson
status.freezed.dart:18
#27     new Status.fromJson
status.dart:111
#28     _$$_StatusFromJson.<anonymous closure>.<anonymous closure>
status.g.dart:55
#29     $checkedConvert
checked_helpers.dart:88
#30     $checkedCreate.checkedConvert
checked_helpers.dart:29
#31     _$$_StatusFromJson.<anonymous closure>
status.g.dart:51
#32     $checkedCreate.<anonymous closure>
checked_helpers.dart:34
#33     $checkedNew
checked_helpers.dart:52
#34     $checkedCreate
checked_helpers.dart:31
#35     _$$_StatusFromJson
status.g.dart:11
#36     new _$_Status.fromJson
status.freezed.dart:588
#37     _$StatusFromJson
status.freezed.dart:18
#38     new Status.fromJson
status.dart:111
#39     BaseService.transformMultiDataResponse.<anonymous closure>
base_service.dart:313
#40     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#41     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#42     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#43     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#44     new List.of (dart:core-patch/array_patch.dart:51:28)
#45     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#46     BaseService.transformMultiDataResponse
base_service.dart:313
#47     _TimelinesV1Service.lookupHomeTimeline
timelines_v1_service.dart:423
<asynchronous suspension>
```

# 7. More information

**Comment by Lisieshy** [comment]
Hello, I am having the exact same issue using mastodon_api 0.6.1 in my Flutter project.

Did you find a solution for that issue?
